### ISSUE TITLE
fetch兼容IE9

### ISSUE THREAD

**Issue by fanxiaowei** [camsong/blog#7]
我在使用fetch-jsonp的时候，使用IE9用来获取数据时，获取不到数据啊，
我是利用redux来管理react的state，这是action.js中的获取所有用户的action
============下面的代码=======
import fetchJsonp from 'fetch-jsonp';
import 'fetch-detector';
import 'fetch-ie8';
require('es6-promise').polyfill();

export const USERFETCHSUCCESS="USERFETCHSUCCESS";
export const USERFETCHERR="USERFETCHERR";

/*==========================获取用户信息reducers+++++++++++++++++++++++++*/
//请求用户数据成功
export function UserFetchSucess(json,singal){
  return {
    type:USERFETCHSUCCESS,
    json,
    singal
  }
}

//请求用户数据失败
export function UserFetchErr(singal){
  return {
    type:USERFETCHERR,
    singal
  }
}

//请求用户数据
export function UserFetchData(){
  return dispatch=>{
    return fetchJsonp('/sys/userAction/selectAllUser')
          .then(res=>{return res.json()})
          .then(data=>{
              dispatch(UserFetchSucess(data,1))
          })
          .catch( err=>{dispatch(UserFetchErr(2))})
  }
}
=-======================求各位大神指教==========
   我是一个应届毕业生，很喜欢react技术，但是苦于没有人来指导，我遇到这个问题已经很久了。

**Comment by rccoder** [comment]
![image](https://cloud.githubusercontent.com/assets/7554325/19226073/cbf800be-8ed8-11e6-92af-96c2bf49cf2a.png)
